name: Tests
on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - medrag_multi_modal/**
      - pyproject.toml

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[dev]"

  lint:
    name: check linting using ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  test-privilege-escalation:
    name: test privilege escalation guardrail
    runs-on: ubuntu-latest
    needs: setup
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: python -m pytest -s tests/test_privilege_escalation.py

  test-prompt-injection-llm:
    name: test prompt injection llm guardrail
    runs-on: ubuntu-latest
    needs: setup
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: python -m pytest -s tests/test_prompt_injection_llm.py
