name: Tests
on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - medrag_multi_modal/**
      - pyproject.toml

jobs:
  lint:
    name: check linting using ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  
  # test-secrets-guardrail:
  #   name: test secrets guardrail
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: |
  #         pip install -U pip
  #         pip install torch --index-url https://download.pytorch.org/whl/cpu
  #         pip install -e ".[dev]"
  #         python -m pytest -s tests/test_secrets_detection.py
  
  test-privilege-escalation:
    name: test privilege escalation
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -U pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e ".[dev]"
          python -m pytest -s tests/test_privilege_escalation.py
